### ISSUE TITLE
Change response code returned to client when they are over limits

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [3scale/apicast#142] opened 2016-11-16 19:26 UTC
##### Current Result
1) Client sends bad key                                       --> got 403 Authentication failed
2) Client sends valid key, but is over rate limits --> got 403 Authentication failed.

This makes errors difficult to debug, as the two different causes are not discriminated.

##### Requested Result
Return 429 "Too many requests"

There maybe documentation pages that will required modification to explain this code has changed in this (insert version of apicast that implements this here) or apicast

##### Additional Information
I believe that this is when Service Management API returns a 409 Conflict with authorizing.

We do not at the moment contemplate the need to customize this code and error message via Admin Portal - so a fixed code and message are all that's requested in this issue.

**Comment by MarkCheshire** [comment] 2016-11-25 15:30
We have survived with the abused 403 for years. I am all for improving this, but I would prefer to take a bit more time and do a proper implementation with the ability to customize the response. The code to handle that was designed in a good extensible manner. The second phase beyond that would be to provide meta data response to the client about the rate limit and the time remaining until the next window.

**Comment by kevprice83** [comment] 2016-11-25 15:55
I agree we can wait. Especially as it seems we can use the `X-3scale` header that **will** be supported [here](https://github.com/3scale/backend/issues/783). This should cover most scenarios in the meantime.

**Comment by andrewdavidmackenzie** [comment] 2016-11-25 15:58
OK.

Will the X-3scale be documented in the trouble-shooting guide. I see this behavior as a trouble-shooting problem for providers....

**Comment by kevprice83** [comment] 2016-11-25 16:01
Once it is supported and documented it makes sense to document it also in the troubleshooting guide.

**Comment by unleashed** [comment] 2016-11-25 16:35
The response header referred by @kevprice83 would be (with the corresponding value):
> 3scale-rejection-reason: limits_exceeded

For this to work the gateway will need to provide a header in its request to backend with the following form:
> 3scale-options: rejection_reason_header=1

and if it not parsing the body, use instead:
> 3scale-options: no_body=1&rejection_reason_header=1

This needs to wait until deployment of the affected backend version, which we are working towards completing today (or given the current time, probably on Monday).

**Comment by unleashed** [comment] 2017-01-26 15:58
Just chipping it to say that the deployment of support for that header happened a while ago.

**Comment by davidor** [comment] 2017-10-09 21:10
This is a duplicate of #368

**Closed by davidor** 2017-10-09 21:10 UTC
Labels: enhancement
