### ISSUE TITLE
[Nigtly Tests] Apicast is not handling provided credentials

### ISSUE THREAD

**Issue by pestanko** [3scale/apicast#811] opened 2018-07-12 08:26 UTC
Apicast is returning  403: Authentication failed for the nightly builds for newly created services using the testsuite or manually created.

##### Version: 

Nightly builds - built from master

##### Steps To Reproduce

1. Create a new service, application plan and application using the current build of the system
2. Try to create a request
3. Get 403

I have manually tested service using the user key but it looks like it failed on each one (RHSSO is currently not working in the nightly tests)

##### Current Result

**Test request failed with HTTP code 403: Authentication failed**

##### Expected Result

Status code: 200

##### Additional Information
**Test results:** https://api-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/3scale-nightly-build/125/testReport/

**Apicast log:** http://pastebin.test.redhat.com/616748
**Apicast Info log:** http://pastebin.test.redhat.com/616757

**Comment by mayorova** [comment] 2018-07-12 08:35
@pestanko Could it be that the same Public Base URL is used for all services, so APIcast always matches with the first one (which maybe has a different authentication option)?

**Comment by davidor** [comment] 2018-07-12 08:35
Hi @pestanko ,
According to the logs, the request that APIcast got is: `GET /favicon.ico`. The user key is in the referrer.
```
2018/07/12 08:09:16 [info] 28#28: *3357 [lua] errors.lua:4: rewrite(): no credentials provided for service 25, client: 10.129.2.1, server: _, request: "GET /favicon.ico 
...
```

**Comment by pestanko** [comment] 2018-07-12 08:50
@davidor Hi sorry I may have missed some log messages, here is just info log.

http://pastebin.test.redhat.com/616757

---
@mayorova No for each service there is unique url.

**Comment by pestanko** [comment] 2018-07-29 16:59
It looks like that current master of the backend or system is somehow incompatible with the current version of the Apicast. 
I think we can close because this issue might not be in the apicast, but I cannot determine where is the issue and why is happening.

**Comment by andrewdavidmackenzie** [comment] 2018-07-30 08:50
While testing this same setup recently, Kevin produces this gist describing how to setup.
https://gist.github.com/kevprice83/29137761b92845b8b5d76f62f6af5d63

And it worked (Thursday last week I think)

**Comment by pestanko** [comment] 2018-07-31 06:51
Hi, @andrewdavidmackenzie I'm not really sure how this one is related to the issue that each policy created in nightly tests is not accessible, as I said, it looks like that there might be some bug somewhere (I suspect it is somewhere in system or backend). 

Our current nightly builds are still building masters of each component, so they are not the same environment in which, we are testing in. 

Our testing environment is:
2.2 GA and apicast is built from master

This environment works as expected.

**Comment by pestanko** [comment] 2018-07-31 07:12
I'm also providing log from the backend:
http://pastebin.test.redhat.com/625105

The weird part is ` 404 - 0.010663886 0 0 0 12 15 3 - "rejection_reason_header=1&no_body=1"`

**Comment by andrewdavidmackenzie** [comment] 2018-07-31 08:04
@davidor @unleashed ^^^

**Comment by davidor** [comment] 2018-08-23 13:02
The problem is in the backend<-->system synchronization of metrics.
Nothing to do with APIcast, so closing this issue.

**Closed by davidor** 2018-08-23 13:02 UTC
