### ISSUE TITLE
Avoid dependency on REDIS

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [3scale/apicast#174] opened 2016-12-05 15:55 UTC
I understand that with OAuth additions we have made that we have introduced a (optional) dependency on REDIS in apicast?

Can someone confirm/deny/explain it a bit more and the need.

I think it would be great it we could find other ways to solve the same need and keep the simple apicast deployment as simple as possible.

**Comment by mayorova** [comment] 2016-12-05 16:01
I am not sure, but I believe it's needed when there is more than 1 instance of APIcast. They need to share the cache to store the temporary code used in OAuth, and then retrieve it.
Not sure we can get rid of it completely.

For sure what would be very good is to abstract the cache calls, and make it possible to switch between Redis, local nginx cache or anything else with just adjusting the configuration.

**Comment by andrewdavidmackenzie** [comment] 2016-12-05 17:20
IMO, if we need more than one (live) APIcast needed then maybe they should be deploying XC - or they will be hammering backend.

If there is more than one apicast (for redundancy or other reasons), then no need to ensure cache is shared (and it won't be HA...).

**Comment by MarkCheshire** [comment] 2016-12-05 18:15
The problem is that in the oauth flow in a subset of the oauth flows the gateway has to maintain state to match the auth code to the access token and client ID. There are basically no single instance gateway deployments in production, so we cannot assume any constraint this dimension. 

Options:
1) manage the oauth dance in a different manner
2) make all oauth a plugin with redis a dependency if that is enabled
3) only make redis a dependency for the specific oauth flows which require it

**Comment by MarkCheshire** [comment] 2016-12-05 18:18
The driver for more than one gateway instance is HA, and usually this is configured in a load balanced active-active mode.

**Comment by andrewdavidmackenzie** [comment] 2016-12-06 15:23
If all this is all true, then the differences between vanilla-apicast and xc are getting smaller and smaller and we should consider that in the roadmap.

More importantly, if I understand things correctly:
- dependency on redis was added (by Pili I think) in the docker compose. This is used in some paths of the OAuth code that was added recently?
- there no dependency on a redis image in the OpenShift template in apicast.
- So, anyone starting apicast (RC1 or HEAD) now in OpenShift will be able to try an OAuth flow that follows a code path that tries to access a non-existent REDIS, and it will all fail.

Is that correct?

**Comment by mayorova** [comment] 2016-12-06 21:26
@andrewdavidmackenzie I think that's correct.

Probably the easiest way to fix this in short term would be to add `REDIS_HOST` and `REDIS_PORT` env vars / params to the OpenShift template, and make it clear in the documentation that having a working instance of Redis running somewhere (`REDIS_HOST:REDIS_PORT`) is a prerequisite for the OAuth authentication method.

**Comment by estevaobk** [comment] 2018-08-31 19:39
Hello,

Do you know if a single shared Redis between multiple APIcasts is supported?

It seems to be according to this article:
https://stackoverflow.com/questions/27217502/using-redis-as-a-cache-storage-for-for-multiple-application-on-the-same-server

But I would like to confirm with you as well.

Thanks.

**Comment by mikz** [comment] 2018-09-03 12:07
@estevaobk that is the point of Redis: to be the shared data store between several instances, so yes.

**Comment by davidor** [comment] 2018-11-08 14:29
Redis is only used in the Oauth2.0 flow that's deprecated, so this is no longer an issue.
Redis can also be used in the rate-limit policy, but it's optional, so closing this issue.

**Closed by davidor** 2018-11-08 14:29 UTC
