### ISSUE TITLE
/dev/std* not accessible by non-root on docker < 1.9.0

### ISSUE THREAD

**Issue by jayenashar** [3scale/apicast#69] opened 2016-09-13 07:28 UTC
nginx fails to read the conf file with `access_log` set to `/dev/stdout`
##### Steps To Reproduce
1. install centos 6
2. install docker (1.7 is the latest supported by the old kernel)
3. create a container using `:latest`
##### Current Result

nginx starts but does not forward any requests to the private URL
##### Expected Result

nginx forwards requests
##### Additional Information
- command to run docker: `docker run --detach --publish=127.0.0.1:319:8080 --name=3scale --env=THREESCALE_PROVIDER_KEY=$THREESCALE_PROVIDER_KEY --env=THREESCALE_ADMIN_URL=https://tripgo-admin.3scale.net quay.io/3scale/gateway`
- relevant nginx output: `2016/09/13 05:48:17 [emerg] 7#0: open() "/dev/stdout" failed (13: Permission denied)`
##### Workaround

maybe this one in /entrypoint.sh: https://github.com/docker/docker/issues/6880#issuecomment-220637337 then point nginx to log to `/tmp/logpipe`

**Comment by mikz** [comment] 2016-09-13 08:18
Not sure how we resolve that in V2 because we dropped dumb-init and want to run just nginx.

**Comment by jmprusi** [comment] 2016-09-13 15:01
We can fix this for the master branch only, I will take a look at the possible workarounds.

**Comment by jayenashar** [comment] 2016-09-14 00:36
I don't totally understand how your docker setup is/will-be, but I see https://github.com/3scale/docker-gateway/blob/v2/entrypoint.sh is still around.  Are you dropping that as well?

**Comment by mikz** [comment] 2016-09-14 05:52
All you can see in v2 branch will ne there. Entrypoint for sure.

**Comment by jayenashar** [comment] 2016-09-14 06:00
can the workaround go in entrypoint.sh?

**Comment by mikz** [comment] 2016-09-14 06:09
The problem is we want want another process like cat reading from fifo because that can die and will not be respawn and will become zombie and nginx logging to fifo can mean performance hit because if the fifo is not consumed fast enough it will stop reviewing traffic.
So we could just log to a file but then we would need log rotation. Really don't know what is the best option but don't see anything obvious.

**Comment by jayenashar** [comment] 2016-09-14 06:37
while i agree that `cat` dying would cause problems, would `cat` die in practice?

is patching nginx an option?  a special `access_log` value that means stdout?

**Comment by mikz** [comment] 2016-09-14 06:41
I have no idea if cat would die in practice and I don't really want to find out.
But, considering the options. If we would opt in for some workaround solution only when we detect /dev/std* is not writeable.
Then the options would be: /dev/null or fifo & cat.

We could default to /dev/null and make fifo & cat opt in on your own risk.

Wdyt?

**Comment by jayenashar** [comment] 2016-09-14 07:22
as a user i'm ok with that, but it sounds like a lot of options to support and detect on your end.

**Comment by mikz** [comment] 2016-09-14 07:25
The other option is just to pipe it to /dev/null if /dev/std* is not writeable without any option.
That would be my preferred way of doing it. Docker 1.7 is legacy and broken on many levels.

**Comment by jayenashar** [comment] 2016-09-14 07:38
that's fine with me as well.  even always /dev/null is fine, too.

**Comment by jmprusi** [comment] 2016-09-14 08:10
Fallback to /dev/null is a good option, I will work on a fix today

**Comment by mikz** [comment] 2016-11-17 14:43
Closed by #76. Reopen if it is still a problem on v2.

**Closed by mikz** 2016-11-17 14:43 UTC
Labels: in progress
